### PR TITLE
feat: add native permission handling for iOS

### PR DESCRIPTION
**Pull request by matinzd**
# **Problem**
Right now in the example app and according to documentation we need to request notification permission when a user opens the app. Sometimes, this behavior is not expected and decreases user experience. 

# **Solution**
Added `requestPermission()` and `registerDeviceForRemoteNotifications()` functions for iOS.

### CODE REVIEW

**Comment by wesleyorbin** [comment]
Hi @matinzd! Thank you for your contribution! We've created a ticket to add this internally and will let you know when it has been released.

**Comment by matinzd** [comment]
> Hi @matinzd! Thank you for your contribution! We've created a ticket to review this internally and will let you know when it has been released.

Thanks! please let us know. There are so many other useful PRs are still pending for a long time.

**Comment by matinzd** [comment]
Any updates on this? @wesleyorbin

**Comment by wesleyorbin** [comment]
Hi @matinzd! Our upcoming Swift SDK is a prerequisite for this feature. We have this on our roadmap to be completed after that is released, but we don't have a timeline we can share at the moment.

**Comment by MaggyH** [comment]
@wesleyorbin  ~ Hi could you please let us know when you guys can release this feature?
Thanks in advance

**Comment by matinzd** [comment]
> @wesleyorbin ~ Hi could you please let us know when you guys can release this feature?
> Thanks in advance

It seems that they have already released it with the latest version. I am gonna close this PR.

**Pull request closed without merging**
