### PR TITLE
Add typescript type definitions

### PR DESCRIPTION
**Pull request by ahanriat**
Hi 👋 

Small **PR** to add **Typescript** type definitions ✨ 

🚀

### CODE REVIEW

**Comment by Bucimis** [comment]
Hi @ahanriat, this is great, many thanks for doing this. We've mirrored the change to our internal repo to do some testing and will keep you updated.

**Comment by Bucimis** [comment]
@ahanriat we just released support using the work in this PR in v1.11.1. Let us know if you're able to successfully use the new definitions and feel free to leave feedback and suggestions.

Thanks again for this contribution - this is awesome stuff that will make life easier for a lot of developers.

**Comment by ahanriat** [comment]
@Bucimis will do today thanks!

**Comment by ahanriat** [comment]
Works like a charm 👌

**Pull request closed without merging**
