### PR TITLE
Adding Typescript definitions

### PR DESCRIPTION
**Pull request by llaine**
Hi guys 👋,
Just a quick PR to add Typescript definitions.
Cheers

### CODE REVIEW

**Comment by tiffanylu** [comment]
Hi @llaine,

Thanks for making this PR! We're aiming to finish reviewing this and get back to you next week. Would that timeline work for you?

Best,
Tiff

**Comment by llaine** [comment]
@tiffanylu sure, just ping me when you guys are ready.

**Comment by tiffanylu** [comment]
Hi @llaine,

Thanks for your contribution! Before committing to maintaining the declaration file by merging this PR, our team would like to get more signal regarding Typescript support. Would you be willing to create an issue for others to +1 or comment on, so we can better understand if this would be useful for our users? In the meantime, you’re welcome to fork our repo. Please let us know if that works for you, and thanks again!

Best,
Tiff

**Comment by tiffanylu** [comment]
Thanks for opening the issue @llaine! If it's okay with you, we're going to close this PR for now until we get some more signal on #20, and reopen accordingly.

Best,
Tiff

**Comment by llaine** [comment]
Sure @tiffanylu, I will also open a PR in https://github.com/DefinitelyTyped/DefinitelyTyped see what they think about it.

**Comment by ahanriat** [comment]
giphy

**Comment by ahanriat** [comment]
This is me right now 😢

**Comment by tiffanylu** [comment]
Thanks @llaine! A separately maintained Typescript definition in a best practices repo like DefinitelyTyped would be a fantastic addition to our React Native bridge. If your DefinitelyTyped PR gets merged, we'd be happy to link out to it. You'd also be welcome to make a documentation/README PR on our repo as well.

**Pull request closed without merging**
