### PR TITLE
Add fixed header and library search paths

### PR DESCRIPTION
**Pull request by tomauty**
Builds upon PR #69 in cases where search might be even more ambiguous.

### CODE REVIEW

**Comment by mlazari** [comment]
Hope to see this merged soon. We need to update to the latest Braze iOS SDK because of the iOS 13 changes ( https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md#breaking ) and this blocks us.

**Comment by Bucimis** [comment]
@mlazari are you not able to add the changes to your local copy of the pbxproj directly?

**Comment by mlazari** [comment]
@Bucimis Yes, I think we can use a forked version of this library with this change included until it's fixed.

**Comment by ivanichoo** [comment]
Hello! Are you going to merge/publish this PR soon? Thanks 🙏

**Comment by ivanichoo** [comment]
👋 🚨

**Comment by Bucimis** [comment]
thanks @tomauty for the contribution and everyone for the discussion! we just released https://github.com/Appboy/appboy-react-sdk/releases/tag/1.17.3 which incorporates this PR and should address this. Let us know how it goes!

**Pull request closed without merging**
